# This is a basic workflow to help you get started with Actions

name: CI
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |

          echo "where am I"
          pwd
          echo "workspace"
          echo ${{github.workspace}}


          #create a DEV branch of this hotfix branch
          # Set your variables
          owner="mickeygousset"
          repo="working-with-branches"
          token="${{secrets.SATOKEN}}"
          base_branch=${{github.head_ref}}
          new_branch=${{github.head_ref}}-dev

          echo $base_branch
          echo $new_branch

          # Get the SHA of the latest commit on the base branch
          sha=$(gh api repos/$owner/$repo/git/ref/heads/$base_branch --jq '.object.sha')
  
          # Create a new reference (branch) with that SHA
          gh api -X POST /repos/$owner/$repo/git/refs -f ref=refs/heads/$new_branch -f sha=$sha

          # Get the SHA of the latest commit on the base branch
          #echo "getting the sha"
          #sha=$(curl -s -H "Authorization: token $token" https://api.github.com/repos/$owner/$repo/git/ref/heads/$base_branch | jq -r '.object.sha')
          #sha=${{github.sha}}
          #echo $sha

          # Create a new reference (branch) with that SHA
          #curl -X POST -H "Authorization: token $token" -d "{\"ref\": \"refs/heads/$new_branch\", \"sha\": \"$sha\"}" https://api.github.com/repos/$owner/$repo/git/refs
          
          

          
